package main

import (
	"context"
	"errors"
	"fmt"
	"io"
	"log"
	"os"
	"path/filepath"
	"strings"
	"time"

	ragagent "github.com/gtkit/go-rag-agent"
)

type basicSession interface {
	Ask(ctx context.Context, query string) (ragagent.Answer, error)
}

type basicAgent interface {
	AddKnowledge(ctx context.Context, src ragagent.KnowledgeSource) error
	GetSession(id string) basicSession
	Close() error
}

var newBasicAgent = func(cfg ragagent.Config) (basicAgent, error) {
	agent, err := ragagent.New(cfg)
	if err != nil {
		return nil, err
	}
	return realBasicAgent{agent: agent}, nil
}

type realBasicAgent struct {
	agent *ragagent.Agent
}

func (a realBasicAgent) AddKnowledge(ctx context.Context, src ragagent.KnowledgeSource) error {
	return a.agent.AddKnowledge(ctx, src)
}

func (a realBasicAgent) GetSession(id string) basicSession {
	return a.agent.GetSession(id)
}

func (a realBasicAgent) Close() error {
	return a.agent.Close()
}

func main() {
	if err := run(context.Background(), os.Stdout, os.Getenv); err != nil {
		log.Fatalf("run basic example: %v", err)
	}
}

func run(ctx context.Context, stdout io.Writer, getenv func(string) string) error {
	knowledgeDir, err := os.MkdirTemp("", "ragagent-knowledge-*")
	if err != nil {
		return fmt.Errorf("make temp knowledge dir: %w", err)
	}
	defer func() {
		_ = os.RemoveAll(knowledgeDir)
	}()

	knowledgeFile := filepath.Join(knowledgeDir, "quickstart.md")
	knowledgeText := []byte("# Quickstart\n\nThis document is generated by examples/basic/main.go.")
	if err := os.WriteFile(knowledgeFile, knowledgeText, 0o600); err != nil {
		return fmt.Errorf("write temp knowledge file: %w", err)
	}

	dataDir := filepath.Join(knowledgeDir, "data")

	cfg, err := configFromEnv(getenv)
	if err != nil {
		return err
	}
	cfg.DataDir = dataDir
	cfg.RequestTimeout = 20 * time.Second
	cfg.ChunkSize = 800
	cfg.ChunkOverlap = 120
	cfg.TopK = 4

	agent, err := newBasicAgent(cfg)
	if err != nil {
		return fmt.Errorf("new agent: %w", err)
	}
	defer func() {
		if closeErr := agent.Close(); closeErr != nil {
			log.Printf("close agent: %v", closeErr)
		}
	}()

	if err := agent.AddKnowledge(ctx, ragagent.DirSource(knowledgeDir)); err != nil {
		return fmt.Errorf("add knowledge: %w", err)
	}

	session := agent.GetSession("team-a")
	answer, err := session.Ask(ctx, "请基于知识库总结接入步骤")
	if err != nil {
		return fmt.Errorf("ask: %w", err)
	}

	if _, err := fmt.Fprintln(stdout, "Scenario: basic embedded setup"); err != nil {
		return fmt.Errorf("write output: %w", err)
	}
	if _, err := fmt.Fprintln(stdout, answer.Text); err != nil {
		return fmt.Errorf("write output: %w", err)
	}
	if _, err := fmt.Fprintf(stdout, "Citations: %d\n", len(answer.Citations)); err != nil {
		return fmt.Errorf("write output: %w", err)
	}
	return nil
}

func configFromEnv(getenv func(string) string) (ragagent.Config, error) {
	cfg := ragagent.Config{
		ChatModel:        strings.TrimSpace(getenv("RAGAGENT_CHAT_MODEL")),
		ChatBaseURL:      strings.TrimSpace(getenv("RAGAGENT_CHAT_BASE_URL")),
		ChatAPIKey:       strings.TrimSpace(getenv("RAGAGENT_CHAT_API_KEY")),
		EmbeddingModel:   strings.TrimSpace(getenv("RAGAGENT_EMBEDDING_MODEL")),
		EmbeddingBaseURL: strings.TrimSpace(getenv("RAGAGENT_EMBEDDING_BASE_URL")),
		EmbeddingAPIKey:  strings.TrimSpace(getenv("RAGAGENT_EMBEDDING_API_KEY")),
	}
	if cfg.EmbeddingBaseURL == "" {
		cfg.EmbeddingBaseURL = cfg.ChatBaseURL
	}
	if cfg.EmbeddingAPIKey == "" {
		cfg.EmbeddingAPIKey = cfg.ChatAPIKey
	}
	if cfg.ChatModel == "" || cfg.ChatBaseURL == "" || cfg.ChatAPIKey == "" || cfg.EmbeddingModel == "" {
		return ragagent.Config{}, errors.New("set RAGAGENT_CHAT_MODEL, RAGAGENT_CHAT_BASE_URL, RAGAGENT_CHAT_API_KEY and RAGAGENT_EMBEDDING_MODEL")
	}
	return cfg, nil
}
