package main

import (
	"context"
	"fmt"
	"log"
	"os"
	"path/filepath"
	"time"

	ragagent "github.com/gtkit/go-rag-agent"
)

func main() {
	ctx := context.Background()
	knowledgeDir, err := os.MkdirTemp("", "ragagent-knowledge-*")
	if err != nil {
		log.Fatalf("make temp knowledge dir: %v", err)
	}
	defer func() {
		_ = os.RemoveAll(knowledgeDir)
	}()

	knowledgeFile := filepath.Join(knowledgeDir, "quickstart.md")
	knowledgeText := []byte("# Quickstart\n\nThis document is generated by examples/basic/main.go.")
	if err := os.WriteFile(knowledgeFile, knowledgeText, 0o600); err != nil {
		log.Fatalf("write temp knowledge file: %v", err)
	}

	dataDir := filepath.Join(knowledgeDir, "data")

	cfg := ragagent.Config{
		ChatModel:        "gpt-4o-mini",
		ChatBaseURL:      "https://api.openai.example/v1",
		ChatAPIKey:       "replace-with-your-chat-key",
		EmbeddingModel:   "text-embedding-3-small",
		EmbeddingBaseURL: "https://api.openai.example/v1",
		EmbeddingAPIKey:  "replace-with-your-embedding-key",
		DataDir:          dataDir,
		RequestTimeout:   20 * time.Second,
		ChunkSize:        800,
		ChunkOverlap:     120,
		TopK:             4,
	}

	agent, err := ragagent.New(cfg)
	if err != nil {
		log.Fatalf("new agent: %v", err)
	}
	defer func() {
		if closeErr := agent.Close(); closeErr != nil {
			log.Printf("close agent: %v", closeErr)
		}
	}()

	if err := agent.AddKnowledge(ctx, ragagent.DirSource(knowledgeDir)); err != nil {
		log.Fatalf("add knowledge: %v", err)
	}

	session := agent.GetSession("team-a")
	answer, err := session.Ask(ctx, "请基于知识库总结接入步骤")
	if err != nil {
		log.Fatalf("ask: %v", err)
	}

	fmt.Println("Answer:")
	fmt.Println(answer.Text)
	fmt.Printf("Citations: %d\n", len(answer.Citations))
}
